### PR TITLE
Homematic

### PR DESCRIPTION
**Pull request by Koshu**
Added Support for Motion Sensors and a few minor fixes

### CODE REVIEW

**Comment by danielperna84** [comment]
@pvizeli is currently making some major improvements to pyhomematic. As soon as he is finished I will test your code for functionality. The existing HA-pyhomematic connection might break at some points.
I will keep you updated.

**Comment by pvizeli** [comment]
The new code support your device with buttons and motion at same time...

**Comment by Koshu** [comment]
Ah ok, then i guess the pull request can be closed, thanks. Is the old homeassistant component still working or are you (two?) already working on the new one? Have a bunch of homematic devices and would help testing and (if helpful) coding.

**Comment by danielperna84** [comment]
I have merged @pvizeli PR into this fork. As he states, your device is functional. Hence I'm closing this PR.
Please test your devices with the current code in this repository.

**Pull request closed without merging**
